import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header() {
  return (
    <header className="bg-slate-500 py-4">
      <div className="container mx-auto x-4">
        <nav className="flex items-center justify-between">
          <div className="flex items-center">
            <Link href="/" className="text-lg font-bold">
              Snowtooth Mountain
            </Link>
          </div>
          <div>
            <Link href="/mountain" className="text-lg font-bold">
              Mountain Info
            </Link>
          </div>
          <div>
            <Link href="/hotels" className="text-lg font-bold">
              Hotel Info
            </Link>
          </div>
          <div>
            <Link href="/contact" className="text-lg font-bold">
              Contact Us
            </Link>
          </div>
        </nav>
      </div>
    </header>
  );
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
